version: "3"
services:
  todo-express-app:
    build: .
    restart: always
    ports:
      - 3030:3030
    environment:
      PORT: 3030
      UrlDB: mongodb://root:example@mongo:27017
      DB_NAME: todos
    volumes:
      - ./:/todo-app
      - /todo-app/redis_api
      - /todo-app/redis_data
      - /todo-app/data-storage/mongo
    depends_on:
      - mongo
      - redis-api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data-storage/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo

  redis-storage:
    image: redis
    restart: always
    volumes:
      - ./redis_data:/data

  redis-api:
    image: node:alpine
    restart: always
    volumes:
      - ./redis_api:/app
    working_dir: /app
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      REDIS_URL: redis://storage
    command: npm run dev
    depends_on:
      - redis-storage
