version: "3"
services:
  todo-express-app:
    image: laps78/todo-simple-express:1.0.2
    restart: always
    ports:
      - 3030:3030
    environment:
      PORT: 3030
      UrlDB: mongodb://root:example@mongo:27017
      DB_NAME: todos
    volumes:
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data-storage/mongo:/data-storage/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
